version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local
