apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: erenmemo/auth
      context: ./
      docker:
        dockerfile: apps/auth/Dockerfile
      sync:
        manual:
          - src: apps/auth
            dest: .
    - image: erenmemo/sendmail
      context: ./
      docker:
        dockerfile: apps/sendmail/Dockerfile
      sync:
        manual:
          - src: apps/sendmail
            dest: .
