apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: erenmemo/auth
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-host
                  key: DATABASE_HOST
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-username
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DATABASE_PASSWORD
            - name: NODE_ENV
              value: development
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
