apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: erenmemo/auth
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: jwt-expires-in
                  key: JWT_EXPIRES_IN
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-issuer
                  key: JWT_ISSUER
            - name: REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: refresh-token-expires-in
                  key: REFRESH_TOKEN_EXPIRES_IN
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-host
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-port
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: REDIS_PASSWORD
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: amqp-url
                  key: AMQP_URL
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: client-url
                  key: CLIENT_URL
            - name: VERIFICATION_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: verification-token-expires-in
                  key: VERIFICATION_TOKEN_EXPIRES_IN
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: domain
                  key: DOMAIN
            - name: NODE_ENV
              value: development
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
