apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendmail-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sendmail
  template:
    metadata:
      labels:
        app: sendmail
    spec:
      containers:
        - name: sendmail
          image: erenmemo/sendmail
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: amqp-url
                  key: AMQP_URL
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: client-url
                  key: CLIENT_URL
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: resend-api-key
                  key: RESEND_API_KEY
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: email
                  key: EMAIL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: node-env
                  key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: sendmail-srv
spec:
  selector:
    app: sendmail
  ports:
    - name: sendmail
      protocol: TCP
      port: 3000
      targetPort: 3000
