apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: erenmemo/product
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-issuer
                  key: JWT_ISSUER
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: amqp-url
                  key: AMQP_URL
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: client-url
                  key: CLIENT_URL
            - name: PUBLIC_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: public-access-key
                  key: PUBLIC_ACCESS_KEY
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-access-key
                  key: SECRET_ACCESS_KEY
            - name: REGION
              valueFrom:
                secretKeyRef:
                  name: region
                  key: REGION
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: BUCKET
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-host
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-port
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: REDIS_PASSWORD
            - name: CLOUDFRONT_URL
              valueFrom:
                secretKeyRef:
                  name: cloudfront-url
                  key: CLOUDFRONT_URL
            - name: CLOUDFRONT_KEY_PAIR_ID
              valueFrom:
                secretKeyRef:
                  name: cloudfront-key-pair-id
                  key: CLOUDFRONT_KEY_PAIR_ID
            - name: CLOUDFRONT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudfront-private-key
                  key: private-key.pem
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: node-env
                  key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  selector:
    app: product
  ports:
    - name: product
      protocol: TCP
      port: 3000
      targetPort: 3000
