apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: erenmemo/shop
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-issuer
                  key: JWT_ISSUER
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: amqp-url
                  key: AMQP_URL
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: client-url
                  key: CLIENT_URL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-host
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-port
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: REDIS_PASSWORD
            - name: CLOUDFRONT_URL
              valueFrom:
                secretKeyRef:
                  name: cloudfront-url
                  key: CLOUDFRONT_URL
            - name: CLOUDFRONT_KEY_PAIR_ID
              valueFrom:
                secretKeyRef:
                  name: cloudfront-key-pair-id
                  key: CLOUDFRONT_KEY_PAIR_ID
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-key
                  key: STRIPE_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-webhook-secret
                  key: STRIPE_WEBHOOK_SECRET
            - name: CLOUDFRONT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudfront-private-key
                  key: private-key.pem
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: node-env
                  key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: shop-srv
spec:
  selector:
    app: shop
  ports:
    - name: shop
      protocol: TCP
      port: 3000
      targetPort: 3000
