name: product-test

on:
  pull_request:
    paths:
      - 'apps/product/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'test'
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AMQP_URL: ${{ secrets.AMQP_URL }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
      PUBLIC_ACCESS_KEY: ${{ secrets.PUBLIC_ACCESS_KEY }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      REGION: ${{ secrets.REGION }}
      BUCKET: ${{ secrets.BUCKET }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npx nx test-unit auth
      - run: npx nx test-int auth
