name: shop-test

on:
  pull_request:
    paths:
      - 'apps/shop/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'test'
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AMQP_URL: ${{ secrets.AMQP_URL }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      CLOUDFRONT_URL: ${{ secrets.CLOUDFRONT_URL }}
      CLOUDFRONT_PRIVATE_KEY: ${{ secrets.CLOUDFRONT_PRIVATE_KEY }}
      CLOUDFRONT_KEY_PAIR_ID: ${{ secrets.CLOUDFRONT_KEY_PAIR_ID }}
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npx nx test-unit shop
      - run: npx nx test-int shop
